apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: prod
replicas:
- count: 4
  name: rest-api-template
namespace: awesome-prod
resources:
- ../../base
patchesStrategicMerge:
- ingress.yml
images:
- name: registry.com/rest-api-template
  newTag: 0.0.1

