apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: dev
replicas:
- count: 2
  name: rest-api-template
namespace: awesome-dev
resources:
- ../../base
patchesStrategicMerge:
- ingress.yml
images:
- name: registry.com/rest-api-template
  newTag: 0.0.2
- name: rest-api-template
  newTag: 0.0.1
